# ==========================================
# APPLICATION CONFIGURATION
# ==========================================
spring.application.name=AquaTrack
server.port=8080

# ==========================================
# POSTGRESQL DATABASE
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/aquatrack
spring.datasource.username=postgres
spring.datasource.password=Radha@2004

spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# FLYWAY
# ==========================================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ==========================================
# LOGGING
# ==========================================
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.SQL=DEBUG


# ==========================================
# JWT
# ==========================================

jwt.secret=ChangeThisToA256BitVeryLongSecretKeyForProduction123456789
jwt.expiration=864000000


# ==========================================
# Spring Mail Configuration
# ==========================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ==========================================
# AquaTrack Mail Configuration
# ==========================================

aquatrack.mail.from=${MAIL_USERNAME}
aquatrack.mail.sender-name=AquaTrack

app.frontend-url=http://localhost:5173