-- ==========================================
-- Create Payments Table
-- ==========================================

CREATE TABLE payments (

                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          water_bill_id BIGINT NOT NULL,

                          amount DECIMAL(10,2) NOT NULL,

                          payment_method VARCHAR(30) NOT NULL,

                          payment_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

                          transaction_id VARCHAR(150) UNIQUE,

                          payment_date DATE NOT NULL,

                          remarks VARCHAR(500),

                          created_at TIMESTAMP NOT NULL,

                          updated_at TIMESTAMP NOT NULL,

                          CONSTRAINT fk_payment_water_bill
                              FOREIGN KEY (water_bill_id)
                                  REFERENCES water_bills(id)
                                  ON DELETE CASCADE

);